### ISSUE TITLE
Docserver not getting document files from Moodle

### ISSUE THREAD

**Issue by aherkst** [ONLYOFFICE/moodle-mod_onlyofficeeditor#54]
I upgraded my Moodle from 3 to 4 and also upgraded the plugin from v2.2 to v4.1.0
Now I get the "Could not be saved" warning, immediately followed by the "Download Failed" error.

On my Document server I have found that whenever I attempt to open a document I get this sort of error in "/var/log/onlyoffice/documentserver/converter/out.log" :
```
[2023-08-21T13:10:29.100] [ERROR] [localhost] [6O3SSx29oNUFS0ijQheS] [383d86008edae3a3a7e68c59c0da6dbe] nodeJS - error downloadFile:url=https://onlyoffice.redacted.customer.domain/pluginfile.php/544889/mod_onlyofficeeditor/content/file-sample_100kB.docx?doc=eXdxdFdQOElyVDNHYmNGdnJPYlN2WHU4R1djMnZFY2xWZDRmcVpPMkhjcz0/eyJ1c2VyaWQiOiIyNDAyOSIsImNvbnRlbnRoYXNoIjoiNjIxNDg1NTA2NTU3NmVjODRhMGZmMWY2ZmEzYTRhNjliZTIwMTIyZSJ9;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:404; headers:{"server":"nginx/1.14.2","date":"Mon, 21 Aug 2023 13:10:29 GMT","content-type":"text/html; charset=utf-8","transfer-encoding":"chunked","connection":"keep-alive","set-cookie":["MoodleSession=van5cdmp7ffs2c4mg72chsobnl; path=/; secure; HttpOnly"],"content-language":"de","content-script-type":"text/javascript","content-style-type":"text/css","x-ua-compatible":"IE=edge","cache-control":"private, pre-check=0, post-check=0, max-age=0, no-transform","pragma":"no-cache","expires":"","x-frame-options":"sameorigin","content-encoding":"gzip"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```
It seems that the Documentserver attempts to fetch the document from my moodle server but moodle fails to provide it.
(https://onlyoffice.redacted.customer.domain/pluginfile.php/544889/mod_onlyofficeeditor/content/file-sample_100kB.docx?doc=eXdxdFdQOElyVDNHYmNGdnJPYlN2WHU4R1djMnZFY2xWZDRmcVpPMkhjcz0/eyJ1c2VyaWQiOiIyNDAyOSIsImNvbnRlbnRoYXNoIjoiNjIxNDg1NTA2NTU3NmVjODRhMGZmMWY2ZmEzYTRhNjliZTIwMTIyZSJ9)

I have confirmed, that the document I use for testing (file-sample_100kB.docx) actually exists on the moodle server, at least it shows up in the mdl_files table after I upload it and create the onlyoffice activity with it.

**Comment by SergeyKorneyev** [comment]
Hello,
If the issue is still relevant, please do the following:
1. Using `wget` or `curl`, check if the Moodle server can reach the Docs server using the address specified in the connection settings and vice versa
2. Check if JWT is configured correctly according to the guide: https://helpcenter.onlyoffice.com/integration/gettingstarted-moodle.aspx

If everything seems fine with the connection and configuration, please also post relevant log records from the Moodle side.

**Comment by merlin02306** [comment]
Have you solved the problem? I encountered the same issue, and here are the Docker logs:
[2024-12-03T14:36:21.725] [ERROR] [localhost] [wO9BNjYDsJs8qrGWMpPv] [c81e728d9d4c2f636f067f89cc14862c] nodeJS - error downloadFile:url=http://10.55.1.3/moodle/pluginfile.php/40205/mod_onlyofficeeditor/content/11.xlsx?doc=dGpKeUJZNVFLbEpiVDBHQWg5eFdjcWZxdzZqcHVkYng4anUwNHBxZkx2Yz0/eyJ1c2VyaWQiOiIyIiwiY29udGVudGhhc2giOiI1NmU3OTY2Y2M0ZWE1NjEwOTE2ODRmM2VhZDAzNzdiZGRmZDE1NTljIn0=;attempt=3;code:null;connect:null Error: Error response: statusCode:404; headers:{"server":"nginx/1.24.0 (Ubuntu)","date":"Tue, 03 Dec 2024 14:36:21 GMT","content-type":"text/html","transfer-encoding":"chunked","connection":"keep-alive","content-encoding":"gzip"};
    at Request.fResponse (/snapshot/server/Common/sources/utils.js)
    at Request.emit (node:events:527:28)
    at Request.onRequestResponse (/snapshot/server/Common/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:494:22)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by merlin02306** [comment]
The Moodle server and the documentation server can access each other.

**Comment by merlin02306** [comment]
The issue has been resolved; I forgot to add the file reading permissions for PHP in Nginx.
